name: Create release drafter and update task

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  kanboard:
    if: ${{ github.event.pull_request.merged }}
    uses: moogur/all-workflows/.github/workflows/kanboard.yml@master
    secrets: inherit
    with:
      kanboard_columns: '132,133,134,135,136,137,-'
      project_type: 'multi_branch'
      event_type: 'merge'

  publish:
    needs: kanboard
    uses: moogur/all-workflows/.github/workflows/deploy_for_frontend.yml@master
    secrets: inherit
