name: Test, lint, build, kanboard

on:
  push:
    branches-ignore:
      - master

jobs:
  kanboard:
    uses: moogur/all-workflows/.github/workflows/kanboard.yml@master
    secrets: inherit
    with:
      kanboard_columns: '132,133,134,135,136,137,-'
      project_type: 'multi_branch'
      event_type: 'push'

  other-actions:
    needs: kanboard
    uses: moogur/all-workflows/.github/workflows/actions_for_push.yml@master
    secrets: inherit
    with:
      skip_tests: 'true'
